spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    #   locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: phoneservice
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/phoneservice"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/phoneservice"
  jpa:
    open-in-view: false
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate:
        ddl-auto: validate
server:
  port: 8081